language: d
d: 
  - dmd
  
before_script:
  - git clone https://github.com/DregginGames/Draon2Dgame.git game
  
script: 
  - dub build -c game
  - dub build -c mapeditor
  - dub build -b ddox -c docs
  
after_success: 
  - bash ./deploy.sh
