rm -rf .dub 
rm -rf docs 
rm -rf *.html
rm -rf docs.json 
rm -rf deployPackage 
rm -rf engine/*.exe 
rm -rf engine/*.lib 
rm -rf engine/*.so 
rm -rf engine/Dragon2D
rm -rf engine/uieditor 
rm -rf engine/mapeditor
rm -rf engine/log.txt
